### ISSUE TITLE
[BUG] Old task with parentId failing to get as 'deleted'

### ISSUE THREAD

**Issue by jbriales** [amazingmarvin/MarvinAPI#27]
**Statement of purpose**

I do solemnly swear (or affirm) that this is an API bug, and not a Marvin bug. For Marvin bugs I would use the in-app "?→Contact Support" feature

**Describe the bug**
I'm working with my database data and for some tasks (old and closed, back from 2019)
I get 
```js
{
  status: 404,
  error: true,
  reason: 'deleted',
  docId: '10cce98f-b4b7-4ab8-bead-4a7230a26101'
}
```
when trying to retrieve its parent as `db.get(doc.parentId)`.

Checking the task in the web app this task appears as being in 'Inbox'.

So, could we get some clarification about the points involved above?

**Comment by amazingmarvin** [comment]
When you delete a category/project, then only open child tasks/projects are deleted. Marvin doesn't update the `parentId` of completed tasks for a number of reasons (not to mention it wouldn't work unless you're in archive mode). Tasks and projects with `parentId="unassigned"` live in the Inbox. Tasks and projects whose parents have been deleted are "orphans" and also appear in the Inbox. Similarly if Marvin detects a cycle (e.g. Category A is in B and B is in C and C is in A), then one or more will appear in the Inbox in order to prevent infinite loops. The reason why Marvin doesn't change the `parentId` as soon as it finds orphans and cycles is to avoid sync conflicts. You can fix cycles/orphans manually or by following [this guide](https://help.amazingmarvin.com/en/articles/4311081-fixing-category-project-cycles-and-orphans). In your case you should probably do it in archive mode!
