### ISSUE TITLE
Document API endpoint for updating Habits

### ISSUE THREAD

**Issue by manmademagic** [amazingmarvin/MarvinAPI#43]
Currently the habit API endpoint is not documented. It would be good to have this information available to be able to use the Marvin API rather than CouchDB directly.

**Comment by mltucker** [comment]
Hi @manmademagic, I have documented this API (https://github.com/amazingmarvin/MarvinAPI/wiki/Marvin-API#habits). Be sure to include `updateDB=true` so that the cloudant database also gets updated. Otherwise the Marvin UI won't be up-to-date until you record again. I haven't tested this yet, so let me know if you run into any issues!
