### ISSUE TITLE
[DOCS] Time tracking starts 5 seconds in the past, ends at correct time

### ISSUE THREAD

**Issue by Erudition** [amazingmarvin/MarvinAPI#44]
**Statement of purpose**

I do solemnly swear (or affirm) that this is an API bug, and not a Marvin bug. For Marvin bugs I would use the in-app "?→Contact Support" feature

**Describe the bug**
I assume this is a "feature", but it is undocumented. When time tracking is started, the returned time is about 5 seconds in the past. I know this is not a difference in server time, because when time tracking is ended, the time is a mere few hundred milliseconds off from the correct time. So it seems that time tracking starts 5 seconds *before* the user hits the start tracking button. (Theoretically this could cause overlap, but I'm guessing you're okay with that. It also makes all sessions at least 5 seconds long, even if they're not.)

**Endpoint(s) in question**
`/api/track`

**Expected behavior**
This to be documented so we don't have to go crazy wondering why we seem to be parsing bad data. And so that we can account for it, and there's evidence so that if one day you decide to change the (negative) delay, we can figure out what happened. :)

**Additional context**
Not a big deal, just wanted to get this written down somewhere, took a while to discover.

**Comment by amazingmarvin** [comment]
OK, so what's going on here is that when you start time tracking, Marvin (on web/desktop) waits 5 seconds before contacting the server, but it does use the time when you clicked (or otherwise started time tracking) so I don't think there could be overlap. This is done since there are a lot of scenarios where you can quickly start time tracking without meaning to, and it makes it so that this "accidental" time tracking doesn't hit the database. For example, if you're in super focus mode and you finish one task, then it would automatically start tracking the next. But possibly you're done working for now so you close super focus mode and stop tracking. It's nice to have this second or two *not* saved as tracked time.

If I ever document exactly how time tracking works then I'll explain this. For now hopefully users will find this issue if they search for it :). Let me know if you have further questions.

**Comment by Erudition** [comment]
That makes perfect sense, thanks!
So the server assumes it was 5 seconds prior because the client always waits 5 seconds. Yeah, sounds like you'd avoid overlaps then, assuming you only ever use one client at a time, and not the API 😄 I was actually hoping you could send the request with the actual timestamp you clicked to start with, not the (usually very close) timestamp the server decides. But then I realized that Marvin's time tracking does not work offline...

**Comment by amazingmarvin** [comment]
The client sends a `timeDiff` parameter which is used to indicate that the time tracking started 5s in the past when you track time from web/desktop (there's actually no delay on mobile since a common usage pattern is to start tracking and then immediately swipe the app away). But you're right that this causes a small inaccuracy because there's a delay in how long it takes to contact the server.

Originally all the time tracking was done offline but then we had a lot of problems with sync conflicts which is why we switched to the online time tracking. Maybe someday we'll support both since we have a lot of offline users!

**Comment by Erudition** [comment]
Oh interesting, well since `timeDiff` is undocumented and I'm not using it, how come I'm getting desktop-only behavior when using the API? How might I get the mobile behavior?
