### ISSUE TITLE
[BUG] addTask endpoint not working

### ISSUE THREAD

**Issue by rowatt** [amazingmarvin/MarvinAPI#8]
I'm just starting to explore the API, so I can't be 100% sure it's a bug, but addTask doesn't seem to be working.

I tried the curl example from the documentation:
```
curl -H 'X-API-Token: XXXXX' -XPOST -d '{"title": "Example API task +today"}' https://serv.amazingmarvin.com/api/addTask
```
but it returns the error "Failed to create task" with status 500 and I don't see the task created in Marvin.

However, the following returns "OK" as expected, with status 200:
```
curl -H 'X-API-Token: XXXXX' -XPOST https://serv.amazingmarvin.com/api/test 
```

The addProject endpoint works as expected too.

Is something wrong with that endpoint, or am I missing something about how this should work?

**Comment by amazingmarvin** [comment]
@rowatt Thanks for the bug report. `/api/addTask` was down between 14:00 UTC yesterday (2021-02-07) and 07:08 UTC today (2021-02-08). Other improvements to the server unintentionally caused `addTask` requests to cloudant to include `_id=""` and `_rev=""`. Cloudant then refused these requests since you can either create documents without an ID or with a non-empty ID, but never `""`.

Sorry about the bug! I plan to add an automated test before new server deployments to avoid this in the future.

**Comment by rowatt** [comment]
Thanks for the info - I just tested again, and it now works as expected.

**Comment by amazingmarvin** [comment]
Thanks for testing it!
